### ISSUE TITLE
Consider using RFC-like language

### ISSUE THREAD

**Issue by lmoureaux** [hep-statistics-serialization-standard/hep-statistics-serialization-standard#8]
Perhaps one of the most obvious features of Internet standards (and drafts) is the consistent use of `MUST`, `SHOULD` and a few other keywords, which was formalized in [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt). This language helps specification writers specify their intentions precisely and readers understand them without ambiguity.

Another common feature in standards documents is the flagging of non-normative sections, typically to provide examples or additional discussion, often starting with `This section is non-normative.`

I think using these language elements would be beneficial to the clarity of the specification.

**Comment by cburgard** [comment]
@lmoureaux I gave it a try in the current draft, using search-and-replace for "optional" and "required" (I don't think we use the others yet). I probably didn't catch all instances yet, but is this along the lines of what you imagined?
More in-depth text-editing will probably be required to consistently used them everywhere also in cases where it's currently not explicated what exactly is meant, but that's something for a long and rainy day of document-editing I suppose.

**Comment by lmoureaux** [comment]
Thanks for working on this @cburgard! I think it's definitely a good step and sticking to this will help readability in the long run.
